pub struct PlayerPlugin;
pub struct CameraPlugin;
pub struct InputPlugin;
pub struct CursorPlugin;
pub struct KeyboardPlugin;
pub struct PlayerMovementPlugin;
pub struct CameraMovementPlugin;
pub struct WorldPlugin;
pub struct MousePlugin;
